@startuml
actor Utente
participant main
entity cdatiCondivisi
entity ThSuono_1
entity ThSuono_2
entity ThSuono_3
entity ThVisualizza

Utente -> main ++ : new

main -> Utente : messaggio 

main -> cdatiCondivisi ** : new
main -> ThSuono_1 ** : new
main -> ThSuono_2 ** : new
main -> ThSuono_3 ** : new
main -> ThVisualizza ** : new

Utente -> main : iniziano rintocchi

main -> ThVisualizza ++ : start
main -> ThSuono_1 ++ : start
main -> ThSuono_2 ++ : start
main -> ThSuono_3 ++ : start

Utente -> main : finiscono rintocchi

ThSuono_1 -> main : return
deactivate ThSuono_1
ThSuono_2 -> main : return
deactivate ThSuono_2
ThSuono_3 -> main : return
deactivate ThSuono_3
ThVisualizza -> main : return
deactivate ThVisualizza

main -> cdatiCondivisi : cdatiCondivisi.waitSemDin()
main -> cdatiCondivisi : cdatiCondivisi.waitSemDon()
main -> cdatiCondivisi : cdatiCondivisi.waitSemDan()

main -> Utente : messaggio
@enduml
